client
	-id (int - automatico)
    -cod_tipo_documento (int - relación a document)
    -des_documento (varchar 15)
    -des_nombre (varchar 30)
    -des_apellido (varchar 30)
    -cod_numero_pais (int - relación a country)
    -num_telefono (varchar 9)
    -des_ruta_foto_perfil (server - varchar(max)) o -img_foto_perfil (blob o varchar(max))
    -ind_estado (boolean)
    -fec_registro (date)
client_address
	-id (int -automatico)
    -cod_cliente (int - relación a client)
    -des_direccion (varchar 500)
    -des_referencia (varchar 500)
    -des_latitud (decimal)
    -des_longitud (decimal)
    -ind_estado (boolean)
    -fec_registro (date)
dealer
	-id (int - automatico)
    -cod_tipo_documento (int - relación a document)
    -des_documento (varchar 15)
    -des_nombre (varchar 30)
    -des_apellido (varchar 30)
    -cod_numero_pais (int - relación a country)
    -num_telefono (varchar 9)
    -num_mac_telefono (varchar 17)
    -num_imei_telefono (varchar 16)
    -cod_tipo_vehiculo (int - relación a vehicle)
    -num_placa_vehiculo (varchar 7)
    -des_ruta_foto_perfil (server - varchar(max)) o -img_foto_perfil (blob o varchar(max))
    -ind_estado (boolean)
    -fec_registro (date)
delivery
	-id (int - automatico) (nro orden)
    -cod_cliente (int - relación a client)
    -cod_repartidor (int - relación a dealer)
    -cod_estado_actual (int - relación a delivery_state) (ultimo estado)
    -cod_tipo_delivery (int - relación a delivery_type)
    -mon_sub_total (decimal)
    -mon_costo_delivery (decimal)
    -mon_total (decimal)
    -fec_registro (date)
delivery_info
	-id (int - automatico)
    -cod_delivery (int - relación a delivery)
    -des_comentario (varchar 500 - comentario del delivery)
    -cod_direccion_origen (int - relación a client_address - opcional) (solo se llena cuando es de tipo encargo)
    -cod_direccion_destino (int - relación a client_address)
    -cod_tipo_pago (int - relación a payment)
    -mon_pagare_efectivo (decimal)
    -fec_registro (date)
delivery_detail
	-id (int - automatico)
    -cod_delivery (int - relación a delivery)
    -cod_producto (int - relación a company_product)
    -num_cantidad (int)
    -mon_total (decimal)
    -fec_registro (date)
delivery_log
	-id (int - automatico)
    -cod_delivery (int - relación a delivery)
    -cod_estado (int - relación a delivery_state)
    -cod_motivo (int - relación a delivery_)
    -des_motivo (varchar 500)
    -fec_registro (date)
company
	-id (int - automatico)
    -cod_tipo_documento (int - relación a document) (tipo RUC estatico)
    -des_ruc (varchar 11)
    -des_razon_social (varchar 500)
    -des_nombre_empresa (varchar 500)
    -des_correo_electronico (varchar 200)
    -des_nombre_propiertario (varchar 200)
    -num_telefono (varchar 9)
    -ind_estado (boolean)
    -fec_registro (date)
system_user
	-
configuration